name: daktela_connector
description: Daktela Connector is SDK by Daktela s.r.o. for Dart/Flutter apps that allows you communicate with standard Daktela V6 REST API.
version: 1.0.1
homepage: https://www.daktela.com/integrace/
repository: https://github.com/Daktela/daktela-v6-dart-connector
issue_tracker: https://github.com/Daktela/daktela-v6-dart-connector/issues

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  http: ^0.13.4


dev_dependencies:
  test: '>=1.15.0 <2.0.0'
  dotenv: ^4.0.1